version: "3.3"

services:
  web:
    build: .
    command: >
      sh -c "
             python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/cearncrm_app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dist
