# Generated by Django 4.0.1 on 2022-02-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='sample@email.com', max_length=256),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default='John', max_length=256),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_emailed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_phoned',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='De', max_length=256),
        ),
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default='+63123456789', max_length=256),
        ),
    ]
